MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/mnt/data-disk2/xinting/jiangyi/top430_finetune/ckps/ckp-top590_freeze4_finetune/model_0055000_for_finetune.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    FREEZE_CONV_BODY_AT: 4
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    POSITIVE_FRACTION: 0.5
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    DETECTIONS_PER_IMG: 300
    USE_FPN: True
    SCORE_THRESH: 0.00
    BATCH_SIZE_PER_IMAGE: 512
    POSITIVE_FRACTION: 0.25
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
#     PREDICTOR: "FPNPredictor"
#     FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    FEATURE_EXTRACTOR: "FPN2MLPCosineFeatureExtractor"
    PREDICTOR: "FPNCosinePredictor"
    NUM_CLASSES: 751 
  ROI_MASK_HEAD:
    USE_BBOX2MASK: True
    USE_MLPMASK: True
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  CLS_AGNOSTIC_BBOX_REG: False
  FEW_SHOT:
    ScaleCls: 10
DATASETS:
  TRAIN: ("lvis_v0.5_train_top750",)
  TEST: ("lvis_v0.5_val_top750",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (35000, 60000)
  MAX_ITER: 71000
  IMS_PER_BATCH: 8
  TEST_PERIOD: 5000  #per 2500 step do validation
  CHECKPOINT_PERIOD: 5000
OUTPUT_DIR: "./ckps/ckp-top750_freeze4_finetune"
TENSORBOARD_EXPERIMENT: "./logs-top750_freeze4_finetune/logs-top750_freeze4"
